name: Android CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Kotlin code style
        run: ./gradlew ktlint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug
      - name: Upload Debug APK (Google Play)
        uses: actions/upload-artifact@v3
        with:
          name: Google Play App (Debug)
          path: ./app/build/outputs/apk/googlePlay/debug/app-googlePlay-debug.apk
      - name: Upload Debug APK (F-Droid)
        uses: actions/upload-artifact@v3
        with:
          name: F-Droid App (Debug)
          path: ./app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk